service: video-handling

frameworkVersion: '3.19.0'

functions: ${file(serverless/functions.yml)}

resources: ${file(serverless/resources.yml)}

useDotenv: true

plugins:
    # - serverless-layers
    - serverless-iam-roles-per-function
    - serverless-webpack

package:
    individually: false
    exclude:
        - node_modules/**

provider:
    name: aws
    runtime: nodejs14.x
    stage: ${opt:stage, "dev"}
    region: ${env:AWS_REGION}
    memorySize: 1024
    timeout: 900
    versionFunctions: false
    deploymentBucket:
        name: ${self:custom.deploymentBucketName}

custom:
    
    deploymentBucketName: ${self:provider.stage}-deployment-bucket-video-handling
    webpack:
        webpackConfig: webpack.config.ts
        includeModules: true





        

