Resources:
    DeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.deploymentBucketName}
    VideoUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-videos
      
  
